version: '3.8'
services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  eureka:
    image: springcloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"