spring:
  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: localhost
    port: 1025
    username: test@example.com
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8081