server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VictorEvseenko/intensive
          default-label: main
          clone-on-start: true
        native:
          search-locations: classpath:/config

  profiles:
    active: native

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/